Fix issue #35 - replace Drupal region setting with custom block.
backdrop-contrib/rules pull request #51
Opened 2019-08-26 16:16 UTC by Graham-72

I have written this PR and am now testing it.
Comments welcome.

2019-08-27 09:44 UTC, herbdool requested changes
I haven't tested this yet so I'll do that soon. But I left a few comments.

2019-08-27 09:44 UTC, herbdool commented on config/rules.settings.json
> +  "rules_log_errors": 3,
This should probably stay "RulesLog::WARN", no? And there doesn't seem to be a reason for other small tweaks to this file. Except for rules_debig_region.

2019-08-27 09:44 UTC, herbdool commented on rules.module
> -    $page[$region]['rules_debug']['#pre_render'] = array('rules_debug_log_pre_render');
Is there a prerender function that is no longer being used?

2019-08-27 09:44 UTC, herbdool commented on config/rules.settings.json
> +  "theme_default": "basis",
The theme variables probably aren't needed. If they are shouldn't they just be called from the core config?

2019-08-28 18:23 UTC, Graham-72 commented on config/rules.settings.json
> +  "rules_log_errors": 3,
Yes, temporary changes accidentally included in this PR, my mistake.

2019-08-28 18:34 UTC, Graham-72 commented on rules.module
> -    $page[$region]['rules_debug']['#pre_render'] = array('rules_debug_log_pre_render');
Yes, `function rules_debug_log_pre_render() ` seems redundant now.

2020-01-05 06:33 UTC, Graham-72 commented on config/rules.settings.json
> +  "theme_default": "basis",
I have made a separate issue for this - #59

2020-01-05 07:11 UTC, Graham-72 commented
Abandoning and closing this PR in favour of a new one - to be created.

2020-01-05 07:11 UTC, closed without merging